version: '3.8'

services:
  db:
    image: postgres:15.0
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: videoCreatorDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  portfolioserverapp:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    container_name: VideoCreatorServer
    restart: always
    ports:
      - "${PORT}:${PORT}"

    environment:
      STATE: ${STATE}
      PORT: ${PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}